{{- if .Values.webui.enabled -}}
{{- if .Values.webui.ingress.enabled -}}
{{- $ingressApiIsStable := eq (include "pgwatch2.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "pgwatch2.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "pgwatch2.ingress.supportsPathType" .) "true" -}}
{{- $fullName := include "pgwatch2.fullname" . -}}
{{- $servicePort := .Values.webui.service.port -}}
{{- $ingressPath := .Values.webui.ingress.path -}}
{{- $ingressPathType := .Values.webui.ingress.pathType -}}
{{- $extraPaths := .Values.webui.ingress.extraPaths -}}
apiVersion: {{ include "pgwatch2.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "pgwatch2.labels" . | nindent 4 }}
{{- if .Values.webui.ingress.labels }}
{{ toYaml .Values.webui.ingress.labels | indent 4 }}
{{- end }}
  {{- if .Values.webui.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.webui.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.webui.ingress.ingressClassName }}
  ingressClassName: {{ .Values.webui.ingress.ingressClassName }}
  {{- end -}}
{{- if .Values.webui.ingress.tls }}
  tls:
{{ tpl (toYaml .Values.webui.ingress.tls) $ | indent 4 }}
{{- end }}
  rules:
  {{- if .Values.webui.ingress.hosts  }}
  {{- range .Values.webui.ingress.hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
{{- if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $fullName }}-webui
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}-webui
              servicePort: {{ $servicePort }}
              {{- end }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
              {{- end }}
            {{- if $ingressPath }}
            path: {{ $ingressPath }}
            {{- end }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
  {{- end -}}
{{- end }}
{{- end }}
